apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-helm-values
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: api-helm-values
    creationPolicy: Owner
  data:
  - secretKey: imageRepository
    remoteRef:
      key: iss-tracker/helm/api
      property: imageRepository
  - secretKey: irsaRoleArn
    remoteRef:
      key: iss-tracker/helm/api
      property: irsaRoleArn