# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  iss-tracker-poller:
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      privileged: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    image:
      repository:
      digest: sha256:50d4a73ee4abe80a9430b8a5e0db4bc49944b5f79cb040db50692a069140fc3e
      imagePullPolicy: IfNotPresent
    # optional env vars
    env:
    - name: DYNAMODB_TABLE
      value: iss-tracker-positions
    - name: AWS_DEFAULT_REGION
      value: us-east-2
    - name: ISS_TRACK_URL
      value: https://api.wheretheiss.at/v1/satellites/25544
    envFrom: {}
    schedule: "* * * * *"
    command: ["python", "poller.py"]
    args: {}
    serviceAccount:
      name: poller
      automountServiceAccountToken: false
      annotations:
        eks.amazonaws.com/role-arn: # inject at helm deploy time
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
    volumes:
    - name: tmp
      emptyDir:
        medium: Memory
    volumeMounts:
    - name: tmp
      mountPath: /tmp
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
    # Because running on fargate, the following components are not necessary
    nodeSelector: {}
    tolerations: {}
    affinity: {}
